version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=ojt_database
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: docker/Dockerfile.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ojt_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: